# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define "nomad-server" do |m|
    m.vm.hostname = "nomad-server"
    m.vm.network "private_network", ip: "192.168.59.100"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = "128"
    end
  end

  (1..3).each do |n|
    name = "node#{n}"
    config.vm.define name do |m|
      m.vm.hostname = name
      m.vm.network "private_network", ip: "192.168.59.10#{n}"
      m.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
    end
  end
end
